/*
 * Uim channel adaptor api
 *
 * uim channel adaptor api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package channeladaptor

// ListContactReq struct for ListContactReq
type ListContactReq struct {
	// 运营号渠道Id
	ProfilePlatformUid string `json:"profilePlatformUid,omitempty"`
	// 运营号渠道自定义Id
	ProfileCustomID string `json:"profileCustomID,omitempty"`
	// 渠道Id
	ServiceID int32 `json:"serviceID,omitempty"`
	// 运营号扩展信息
	Extra string `json:"extra,omitempty"`
}
