/*
 * Uim channel adaptor api
 *
 * uim channel adaptor api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package channeladaptor

// AddContactEvent struct for AddContactEvent
type AddContactEvent struct {
	// 渠道id
	ServiceID int32 `json:"serviceID,omitempty"`
	// 运营号渠道Id
	ProfilePlatformUid string  `json:"profilePlatformUid,omitempty"`
	AddChannel         string  `json:"addChannel,omitempty"`
	AddTime            int64   `json:"addTime,omitempty"`
	Contact            Contact `json:"contact,omitempty"`
}
