/*
 * Uim channel adaptor api
 *
 * uim channel adaptor api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package channeladaptor

// SendCommandReq struct for SendCommandReq
type SendCommandReq struct {
	// 渠道id
	ServiceID int32 `json:"serviceID,omitempty"`
	// 命令类型
	CommandType string `json:"commandType,omitempty"`
	// 命令内容
	Body map[string]interface{} `json:"body,omitempty"`
}
