/*
 * Uim channel adaptor api
 *
 * uim channel adaptor api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package channeladaptor

// ProfileDetailReq struct for ProfileDetailReq
type ProfileDetailReq struct {
	// 联系人渠道id
	ProfilePlatformUid string `json:"profilePlatformUid,omitempty"`
	// 联系人渠道自定义id
	ProfileCustomUid string `json:"profileCustomUid,omitempty"`
	// 渠道id
	ServiceID int32 `json:"serviceID,omitempty"`
	// 扩展信息
	Extra string `json:"extra,omitempty"`
}
