/*
 * Uim channel adaptor api
 *
 * uim channel adaptor api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package channeladaptor

// InlineResponse2005 struct for InlineResponse2005
type InlineResponse2005 struct {
	Code int32          `json:"code,omitempty"`
	Msg  string         `json:"msg,omitempty"`
	Data SendCommandRsp `json:"data,omitempty"`
}
