/*
 * Uim channel adaptor api
 *
 * uim channel adaptor api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package channeladaptor

// SendMessageReq struct for SendMessageReq
type SendMessageReq struct {
	// 租户Id
	TenantId string `json:"tenantId,omitempty"`
	// 运营号渠道Id
	ProfilePlatformUid string `json:"profilePlatformUid,omitempty"`
	// 联系人渠道Id
	ContactPlatformUid string `json:"contactPlatformUid,omitempty"`
	// 群组渠道Id
	PlatformGid string `json:"platformGid,omitempty"`
	// 消息方向 1 接收 2 发送
	Direction int32 `json:"direction,omitempty"`
	// 消息类型
	MessageType int32 `json:"messageType,omitempty"`
	// 会话类型
	SessionType int32 `json:"sessionType,omitempty"`
	// 消息内容
	Content string `json:"content,omitempty"`
	// 渠道Id
	ServiceID int32 `json:"serviceID,omitempty"`
}
