/*
 * Uim channel adaptor api
 *
 * uim channel adaptor api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package channeladaptor

// SendCommandRsp struct for SendCommandRsp
type SendCommandRsp struct {
	// 渠道id
	ServiceID int32 `json:"serviceID,omitempty"`
	// 命令类型
	CommandType string `json:"commandType,omitempty"`
	// 命令响应内容
	Data map[string]interface{} `json:"data,omitempty"`
}
