/*
 * Uim channel adaptor api
 *
 * uim channel adaptor api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package channeladaptor

// DelContactEvent struct for DelContactEvent
type DelContactEvent struct {
	// 渠道id
	ServiceID int32 `json:"serviceID,omitempty"`
	// 运营号渠道Id
	ProfilePlatformUid string `json:"profilePlatformUid,omitempty"`
	DelTime            int64  `json:"delTime,omitempty"`
	ContactPlatformUid string `json:"contactPlatformUid,omitempty"`
}
