/*
 * Uim channel adaptor api
 *
 * uim channel adaptor api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package channeladaptor

// UpdateProfileReq struct for UpdateProfileReq
type UpdateProfileReq struct {
	// 运营号渠道id
	ProfilePlatformUid string `json:"profilePlatformUid,omitempty"`
	// 运营号渠道自定义id
	ProfileCustomUid string `json:"profileCustomUid,omitempty"`
	// 渠道id
	ServiceID int32 `json:"serviceID,omitempty"`
	// 更新类型
	UpdateType string `json:"updateType,omitempty"`
	// 扩展信息
	Extra   string  `json:"extra,omitempty"`
	Profile Profile `json:"profile,omitempty"`
}
