/*
 * Uim channel adaptor api
 *
 * uim channel adaptor api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package channeladaptor

// AdaptorApiEvent struct for AdaptorApiEvent
type AdaptorApiEvent struct {
	Type  string                 `json:"type,omitempty"`
	Token string                 `json:"token,omitempty"`
	Event map[string]interface{} `json:"event,omitempty"`
}
