/*
 * Uim channel adaptor api
 *
 * uim channel adaptor api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package channeladaptor

// Profile struct for Profile
type Profile struct {
	Id              string   `json:"id,omitempty"`
	ContactId       string   `json:"contactId,omitempty"`
	PlatformUid     string   `json:"platformUid,omitempty"`
	PlatformUid2    int64    `json:"platformUid2,omitempty"`
	CustomID        string   `json:"customID,omitempty"`
	Nickname        string   `json:"nickname,omitempty"`
	Avatar          string   `json:"avatar,omitempty"`
	Gender          string   `json:"gender,omitempty"`
	Country         string   `json:"country,omitempty"`
	State           string   `json:"state,omitempty"`
	City            string   `json:"city,omitempty"`
	Signature       string   `json:"signature,omitempty"`
	Mobilephone     string   `json:"mobilephone,omitempty"`
	ServiceID       int32    `json:"serviceID,omitempty"`
	DeviceID        string   `json:"deviceID,omitempty"`
	Online          int32    `json:"online,omitempty"`
	AppVersion      string   `json:"appVersion,omitempty"`
	Balance         int64    `json:"balance,omitempty"`
	Qrcode          string   `json:"qrcode,omitempty"`
	ContactCount    int32    `json:"contactCount,omitempty"`
	Extra           string   `json:"extra,omitempty"`
	Tags            []string `json:"tags,omitempty"`
	PlatformTags    []string `json:"platformTags,omitempty"`
	ProductID       int32    `json:"productID,omitempty"`
	HeartbeatTime   int64    `json:"heartbeatTime,omitempty"`
	VirtualDeviceID string   `json:"virtualDeviceID,omitempty"`
	TenantId        string   `json:"tenantId,omitempty"`
	Deleted         int32    `json:"deleted,omitempty"`
	Status          int32    `json:"status,omitempty"`
	CorpId          string   `json:"corpId,omitempty"`
}
