/*
 * Uim channel adaptor api
 *
 * uim channel adaptor api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package channeladaptor

// Contact struct for Contact
type Contact struct {
	// 联系人id
	Id string `json:"id,omitempty"`
	// 运营号渠道id
	PlatformUid string `json:"platformUid,omitempty"`
	// 运营号渠道自定义id
	CustomID string `json:"customID,omitempty"`
	// 昵称
	Nickname string `json:"nickname,omitempty"`
	// 头像
	Avatar string `json:"avatar,omitempty"`
	// 性别
	Gender int32 `json:"gender,omitempty"`
	// 国家
	Country string `json:"country,omitempty"`
	// 省份
	State string `json:"state,omitempty"`
	// 城市
	City string `json:"city,omitempty"`
	// 签名
	Signature string `json:"signature,omitempty"`
	// 类型
	Type int32 `json:"type,omitempty"`
	// 渠道id
	ServiceID int32 `json:"serviceID,omitempty"`
	// 扩展信息
	Extra string `json:"extra,omitempty"`
	// 标签
	Tags []string `json:"tags,omitempty"`
}
